#!/bin/bash
#
# Regenerate SWIG wrappers for all supported languages
# 
# This script regenerates the Java, C#, and Python bindings from libplctag.h
# It requires SWIG to be installed: brew install swig (macOS), apt install swig (Linux)
#

set -e

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Check if SWIG is installed
if ! command -v swig &> /dev/null; then
    echo "Error: SWIG is not installed or not in PATH"
    echo "Install SWIG with:"
    echo "  macOS: brew install swig"
    echo "  Linux: apt install swig"
    echo "  Or download from: http://www.swig.org"
    exit 1
fi

SWIG_VERSION=$(swig -version | grep "SWIG Version" | awk '{print $3}')
echo "Using SWIG $SWIG_VERSION"

# Create output directories
mkdir -p "$SCRIPT_DIR/generated/java"
mkdir -p "$SCRIPT_DIR/generated/csharp"
mkdir -p "$SCRIPT_DIR/generated/python"

HEADER_DIR="$SCRIPT_DIR/../libplctag/lib"

echo "================================"
echo "Generating Java bindings..."
echo "================================"
swig -java -package com.libplctag \
    -outdir "$SCRIPT_DIR/generated/java" \
    -o "$SCRIPT_DIR/generated/java/libplctag_wrap.cxx" \
    -I"$HEADER_DIR" \
    "$SCRIPT_DIR/libplctag.i"
echo "✓ Java bindings generated in: generated/java/"

echo ""
echo "================================"
echo "Generating C# bindings..."
echo "================================"
swig -csharp -dllimport libplctag \
    -outdir "$SCRIPT_DIR/generated/csharp" \
    -o "$SCRIPT_DIR/generated/csharp/libplctag_wrap.cxx" \
    -I"$HEADER_DIR" \
    "$SCRIPT_DIR/libplctag.i"
echo "✓ C# bindings generated in: generated/csharp/"

echo ""
echo "================================"
echo "Generating Python bindings..."
echo "================================"
swig -python \
    -outdir "$SCRIPT_DIR/generated/python" \
    -o "$SCRIPT_DIR/generated/python/libplctag_wrap.cxx" \
    -I"$HEADER_DIR" \
    "$SCRIPT_DIR/libplctag.i"
echo "✓ Python bindings generated in: generated/python/"

echo ""
echo "================================"
echo "All wrappers generated successfully!"
echo "================================"
echo ""
echo "Next steps:"
echo "  - Java:   Compile native wrapper and JAR files"
echo "  - C#:     Compile managed assemblies with csc"
echo "  - Python: Build native extension module"
echo ""
echo "See README_AUTOGENERATED.md for details on building each wrapper."
